// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCV4WNXeFvrORpnWFGE4mVOqe75hB70XgM',
    appId: '1:532418010716:android:1daa6722fd02c646d69099',
    messagingSenderId: '532418010716',
    projectId: 'habit-boost-fe69a',
    storageBucket: 'habit-boost-fe69a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAL-VUsnIyltCB6hloGR-Ew4dneLp5Lqc8',
    appId: '1:532418010716:ios:373f9f3e006c7708d69099',
    messagingSenderId: '532418010716',
    projectId: 'habit-boost-fe69a',
    storageBucket: 'habit-boost-fe69a.firebasestorage.app',
    iosBundleId: 'com.example.habitBoost',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAL-VUsnIyltCB6hloGR-Ew4dneLp5Lqc8',
    appId: '1:532418010716:ios:373f9f3e006c7708d69099',
    messagingSenderId: '532418010716',
    projectId: 'habit-boost-fe69a',
    storageBucket: 'habit-boost-fe69a.firebasestorage.app',
    iosBundleId: 'com.example.habitBoost',
  );
}
